export const NOTIFICATION_CHANNELS = ['IN_APP', 'PUSH', 'EMAIL', 'SMS', 'REALTIME'] as const;
export type NotificationChannel = (typeof NOTIFICATION_CHANNELS)[number];

export const NOTIFICATION_PRIORITIES = ['LOW', 'NORMAL', 'HIGH', 'CRITICAL'] as const;
export type NotificationPriority = (typeof NOTIFICATION_PRIORITIES)[number];

export const NOTIFICATION_STATUSES = [
  'QUEUED',
  'PROCESSING',
  'SENT',
  'DELIVERED',
  'READ',
  'FAILED',
  'EXPIRED',
  'CANCELLED',
] as const;
export type NotificationStatus = (typeof NOTIFICATION_STATUSES)[number];

export const NOTIFICATION_CATEGORIES = [
  'account',
  'order',
  'delivery',
  'restaurant',
  'rider',
  'payment',
  'security',
  'promotional',
] as const;
export type NotificationCategory = (typeof NOTIFICATION_CATEGORIES)[number];

export const NOTIFICATION_EVENT_TYPES = {
  // ACCOUNT
  USER_REGISTERED: 'USER_REGISTERED',
  EMAIL_VERIFICATION: 'EMAIL_VERIFICATION',
  PHONE_VERIFICATION: 'PHONE_VERIFICATION',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  PASSWORD_RESET: 'PASSWORD_RESET',
  NEW_LOGIN: 'NEW_LOGIN',
  SECURITY_ALERT: 'SECURITY_ALERT',

  // ORDER
  ORDER_PLACED: 'ORDER_PLACED',
  ORDER_ACCEPTED: 'ORDER_ACCEPTED',
  ORDER_REJECTED: 'ORDER_REJECTED',
  ORDER_PREPARING: 'ORDER_PREPARING',
  ORDER_READY: 'ORDER_READY',
  ORDER_CANCELLED: 'ORDER_CANCELLED',
  ORDER_DELIVERED: 'ORDER_DELIVERED',
  ORDER_PAYMENT_SUCCESS: 'ORDER_PAYMENT_SUCCESS',
  ORDER_PAYMENT_FAILED: 'ORDER_PAYMENT_FAILED',
  ORDER_REFUND_INITIATED: 'ORDER_REFUND_INITIATED',
  ORDER_REFUND_COMPLETED: 'ORDER_REFUND_COMPLETED',

  // DELIVERY
  RIDER_ASSIGNED: 'RIDER_ASSIGNED',
  RIDER_ACCEPTED: 'RIDER_ACCEPTED',
  RIDER_ARRIVING: 'RIDER_ARRIVING',
  RIDER_ARRIVED: 'RIDER_ARRIVED',
  ORDER_PICKED_UP: 'ORDER_PICKED_UP',
  ORDER_OUT_FOR_DELIVERY: 'ORDER_OUT_FOR_DELIVERY',
  DELIVERY_DELAYED: 'DELIVERY_DELAYED',
  RIDER_NEAR_DESTINATION: 'RIDER_NEAR_DESTINATION',
  DELIVERY_COMPLETED: 'DELIVERY_COMPLETED',

  // RESTAURANT
  NEW_ORDER: 'NEW_ORDER',
  ORDER_CANCELLED_BY_CUSTOMER: 'ORDER_CANCELLED_BY_CUSTOMER',
  RESTAURANT_STATUS_CHANGED: 'RESTAURANT_STATUS_CHANGED',
  MENU_ITEM_UNAVAILABLE: 'MENU_ITEM_UNAVAILABLE',
  RESTAURANT_VERIFICATION_UPDATE: 'RESTAURANT_VERIFICATION_UPDATE',

  // RIDER
  NEW_DELIVERY_OFFER: 'NEW_DELIVERY_OFFER',
  DELIVERY_ACCEPTED: 'DELIVERY_ACCEPTED',
  DELIVERY_CANCELLED: 'DELIVERY_CANCELLED',
  SURGE_ALERT: 'SURGE_ALERT',
  SHIFT_REMINDER: 'SHIFT_REMINDER',
  DOCUMENT_EXPIRING: 'DOCUMENT_EXPIRING',
  ACCOUNT_STATUS_CHANGED: 'ACCOUNT_STATUS_CHANGED',
  PAYOUT_COMPLETED: 'PAYOUT_COMPLETED',

  // PAYMENTS
  PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYOUT_PENDING: 'PAYOUT_PENDING',
  PAYOUT_FAILED: 'PAYOUT_FAILED',
  REFUND_COMPLETED: 'REFUND_COMPLETED',
} as const;

export type NotificationEventType = (typeof NOTIFICATION_EVENT_TYPES)[keyof typeof NOTIFICATION_EVENT_TYPES];

export const DEVICE_PLATFORMS = ['web', 'android', 'ios'] as const;
export type DevicePlatform = (typeof DEVICE_PLATFORMS)[number];

export const DEFAULT_LOCALE = 'en-IN';
