export const TRACKING_CONSTANTS = {
  DEFAULT_AVERAGE_SPEED_KMH: 25.0, // Average urban delivery speed 25 km/h
  LOCATION_FRESHNESS_THRESHOLD_SECONDS: 60,
  GEOFENCE_RADIUS_METERS: 100, // 100 meters boundary trigger
} as const;

export const TRACKING_ERROR_CODES = {
  TRACKING_SESSION_NOT_FOUND: 'TRACKING_SESSION_NOT_FOUND',
  UNAUTHORIZED_TRACKING_ACCESS: 'UNAUTHORIZED_TRACKING_ACCESS',
  TRACKING_SESSION_EXPIRED: 'TRACKING_SESSION_EXPIRED',
  INVALID_LOCATION_COORDINATES: 'INVALID_LOCATION_COORDINATES',
} as const;
