import type {
  AppConnector,
  WebhookEndpoint,
  WebhookDeliveryLog,
  AutomationRule,
  TriggerDefinition,
  ActionDefinition,
  ApiKeyCredentials,
  SyncHealthMetrics,
  IntegrationActivityLog,
  MarketplaceApp,
  SmartAIInsight,
} from '../types/integrations';

// ─── Initial App Connectors ───────────────────────────────────────────────────
export const INITIAL_CONNECTORS: AppConnector[] = [
  {
    id: 'app-stripe',
    name: 'Stripe Payments',
    category: 'payment',
    description: 'Process online customer checkout payments and automated refund dispatches.',
    icon: '💳',
    developer: 'Stripe, Inc.',
    version: 'v2026.04',
    status: 'connected',
    isPopular: true,
    isFeatured: true,
    connectedAt: '2026-06-12 10:30',
    lastSyncAt: '2 mins ago',
    permissions: ['read:transactions', 'write:refunds', 'manage:webhooks'],
    docsUrl: 'https://stripe.com/docs',
    config: { apiKey: 'pk_live_51M***902', environment: 'production', autoSync: true },
  },
  {
    id: 'app-razorpay',
    name: 'Razorpay PG',
    category: 'payment',
    description: 'UPI, NetBanking, and credit card payments connector for Indian dining locations.',
    icon: '⚡',
    developer: 'Razorpay Software',
    version: 'v3.2.1',
    status: 'connected',
    isPopular: true,
    connectedAt: '2026-06-15 14:20',
    lastSyncAt: '5 mins ago',
    permissions: ['read:payments', 'write:payouts'],
    config: { apiKey: 'rzp_live_891***', environment: 'production', autoSync: true },
  },
  {
    id: 'app-dunzo',
    name: 'Dunzo Delivery Express',
    category: 'delivery',
    description: 'On-demand hyper-local courier dispatch integration for swift merchant delivery.',
    icon: '🛵',
    developer: 'Dunzo Digital',
    version: 'v1.9.0',
    status: 'connected',
    connectedAt: '2026-07-01 09:15',
    lastSyncAt: '12 mins ago',
    permissions: ['write:dispatch', 'read:tracking'],
    config: { environment: 'production', autoSync: true },
  },
  {
    id: 'app-whatsapp',
    name: 'WhatsApp Business API',
    category: 'messaging',
    description: 'Automated WhatsApp order confirmation alerts and customer status notifications.',
    icon: '💬',
    developer: 'Meta Platforms',
    version: 'v18.0',
    status: 'connected',
    isPopular: true,
    connectedAt: '2026-06-20 11:45',
    lastSyncAt: '1 min ago',
    permissions: ['send:messages', 'read:templates'],
    config: { apiKey: 'EAAG91***', environment: 'production', autoSync: true },
  },
  {
    id: 'app-tally',
    name: 'Tally Prime ERP',
    category: 'accounting',
    description: 'Automated ledger synchronization for GST invoicing and daily financial accounts.',
    icon: '📊',
    developer: 'Tally Solutions',
    version: 'v4.1',
    status: 'connected',
    connectedAt: '2026-07-10 16:00',
    lastSyncAt: '30 mins ago',
    permissions: ['write:vouchers', 'read:ledgers'],
    config: { environment: 'production', autoSync: true },
  },
  {
    id: 'app-petpooja',
    name: 'Petpooja POS Connector',
    category: 'pos',
    description: 'Two-way kitchen terminal sync between Feasto KDS and billing desktop POS.',
    icon: '🖥️',
    developer: 'Petpooja Systems',
    version: 'v5.0.2',
    status: 'degraded',
    connectedAt: '2026-07-05 08:30',
    lastSyncAt: '45 mins ago',
    permissions: ['read:orders', 'write:menu_status'],
    config: { environment: 'production', autoSync: true },
  },
  {
    id: 'app-starprint',
    name: 'Star Micronics Thermal Printers',
    category: 'printer',
    description: 'Direct ESC/POS network thermal printing for kitchen tickets and billing counter receipts.',
    icon: '🖨️',
    developer: 'Star Micronics',
    version: 'v2.8',
    status: 'connected',
    connectedAt: '2026-06-10 12:00',
    lastSyncAt: 'Just now',
    permissions: ['write:print_job'],
    config: { environment: 'production', autoSync: true },
  },
  {
    id: 'app-salesforce',
    name: 'Salesforce Marketing Cloud',
    category: 'crm',
    description: 'Sync dining guest profiles, lifetime order history, and targeted promotional campaigns.',
    icon: '☁️',
    developer: 'Salesforce',
    version: 'v60.0',
    status: 'disconnected',
    permissions: ['read:customers', 'write:leads'],
  },
];

// ─── Initial Webhook Endpoints ────────────────────────────────────────────────
export const INITIAL_WEBHOOKS: WebhookEndpoint[] = [
  {
    id: 'wh-1',
    name: 'Production Orders Gateway',
    url: 'https://api.restaurant.feasto.food/v1/webhooks/orders',
    secret: 'whsec_8f9210a9c84e271b9034',
    status: 'active',
    subscribedEvents: ['order.created', 'order.accepted', 'order.ready', 'order.completed'],
    createdAt: '2026-06-01',
    lastDeliveredAt: '2 mins ago',
    failureRatePct: 0.2,
    totalDeliveries: 4280,
    environment: 'production',
  },
  {
    id: 'wh-2',
    name: 'Inventory & Low Stock Dispatcher',
    url: 'https://hooks.inventory-partner.com/feasto/stock',
    secret: 'whsec_3b1189ac721ef900214c',
    status: 'active',
    subscribedEvents: ['inventory.low_stock', 'inventory.out_of_stock'],
    createdAt: '2026-06-14',
    lastDeliveredAt: '18 mins ago',
    failureRatePct: 0.0,
    totalDeliveries: 640,
    environment: 'production',
  },
  {
    id: 'wh-3',
    name: 'Customer CRM Sync Endpoint',
    url: 'https://crm.restaurant-group.io/webhook/feasto',
    secret: 'whsec_99182374bbcca901237e',
    status: 'failing',
    subscribedEvents: ['customer.created', 'review.received'],
    createdAt: '2026-07-02',
    lastDeliveredAt: '1 hour ago',
    failureRatePct: 14.8,
    totalDeliveries: 190,
    environment: 'production',
  },
];

// ─── Initial Webhook Delivery Logs ────────────────────────────────────────────
export const INITIAL_DELIVERY_LOGS: WebhookDeliveryLog[] = [
  {
    id: 'log-101',
    endpointId: 'wh-1',
    endpointName: 'Production Orders Gateway',
    event: 'order.created',
    statusCode: 200,
    executionTimeMs: 142,
    payloadSnippet: '{"orderId":"#1809","amount":445,"status":"preparing"}',
    timestamp: '2 mins ago',
    status: 'success',
    attemptCount: 1,
  },
  {
    id: 'log-102',
    endpointId: 'wh-1',
    endpointName: 'Production Orders Gateway',
    event: 'order.completed',
    statusCode: 200,
    executionTimeMs: 98,
    payloadSnippet: '{"orderId":"#1807","amount":540,"status":"delivered"}',
    timestamp: '15 mins ago',
    status: 'success',
    attemptCount: 1,
  },
  {
    id: 'log-103',
    endpointId: 'wh-3',
    endpointName: 'Customer CRM Sync Endpoint',
    event: 'review.received',
    statusCode: 504,
    executionTimeMs: 5000,
    payloadSnippet: '{"reviewId":"rev-440","rating":5,"comment":"Excellent risotto!"}',
    timestamp: '1 hour ago',
    status: 'failed',
    responseBody: '504 Gateway Timeout: Endpoint did not respond within 5000ms',
    attemptCount: 3,
  },
];

// ─── Trigger Definitions Catalog ──────────────────────────────────────────────
export const TRIGGER_DEFINITIONS: TriggerDefinition[] = [
  { type: 'order.created', label: 'New Order Created', category: 'orders', description: 'Triggers when a customer submits a new order ticket.', availableVariables: ['orderId', 'totalAmount', 'customerName', 'items'] },
  { type: 'order.accepted', label: 'Order Accepted by Kitchen', category: 'orders', description: 'Triggers when kitchen staff confirms order receipt.', availableVariables: ['orderId', 'prepTimeMinutes'] },
  { type: 'order.delayed', label: 'Order Preparation Delayed (>25m)', category: 'orders', description: 'Triggers when kitchen preparation passes the SLA threshold.', availableVariables: ['orderId', 'elapsedMinutes'] },
  { type: 'order.ready', label: 'Order Marked Ready for Pickup', category: 'orders', description: 'Triggers when kitchen marks dish ready for runner.', availableVariables: ['orderId', 'pickupCode'] },
  { type: 'order.completed', label: 'Order Delivered / Completed', category: 'orders', description: 'Triggers when order is successfully handed off.', availableVariables: ['orderId', 'deliveryTime'] },
  { type: 'inventory.low_stock', label: 'Ingredient Low Stock Alert', category: 'inventory', description: 'Triggers when ingredient stock falls below safety minimum.', availableVariables: ['ingredientName', 'currentStock', 'unit'] },
  { type: 'inventory.out_of_stock', label: 'Item Auto-Marked Out of Stock', category: 'inventory', description: 'Triggers when an item stock reaches 0.', availableVariables: ['itemName', 'menuId'] },
  { type: 'customer.created', label: 'New Guest Profile Registered', category: 'customer', description: 'Triggers when a new customer creates an account.', availableVariables: ['customerId', 'email', 'phone'] },
  { type: 'review.received', label: 'New Customer Rating / Review', category: 'customer', description: 'Triggers when a diner submits a review score.', availableVariables: ['reviewId', 'rating', 'comment'] },
  { type: 'invoice.paid', label: 'Payout Invoice Settled', category: 'finance', description: 'Triggers when daily payout is deposited into bank account.', availableVariables: ['invoiceId', 'payoutAmount'] },
];

// ─── Action Definitions Catalog ───────────────────────────────────────────────
export const ACTION_DEFINITIONS: ActionDefinition[] = [
  { type: 'send_notification', label: 'Send Dashboard Notification', description: 'Broadcast alert to merchant control desk.', targetSystem: 'Feasto Portal' },
  { type: 'send_whatsapp' as any, label: 'Send WhatsApp Business Message', description: 'Dispatch WhatsApp template to customer or manager.', targetSystem: 'WhatsApp Cloud API' },
  { type: 'send_email', label: 'Send Automated Email', description: 'Dispatch formatted HTML email message.', targetSystem: 'Email Gateway' },
  { type: 'send_sms', label: 'Send SMS Alert', description: 'Send high-priority SMS text message.', targetSystem: 'Twilio SMS' },
  { type: 'update_inventory', label: 'Update Stock Levels', description: 'Adjust ingredient quantities automatically.', targetSystem: 'Feasto Inventory' },
  { type: 'change_menu_status', label: 'Toggle Dish Availability', description: 'Mark item in stock or out of stock.', targetSystem: 'Feasto Menu Engine' },
  { type: 'trigger_webhook', label: 'Dispatch Custom Webhook', description: 'Post JSON payload to external URL.', targetSystem: 'External Endpoint' },
];

// ─── Initial Automation Rules ─────────────────────────────────────────────────
export const INITIAL_AUTOMATIONS: AutomationRule[] = [
  {
    id: 'rule-1',
    title: 'Instant WhatsApp Order Confirmation',
    description: 'Send automated WhatsApp order summary to customer upon payment receipt.',
    triggerEvent: 'order.created',
    action: 'send_sms',
    actionConfig: { template: 'order_received_v1' },
    isActive: true,
    runCount: 1240,
    lastTriggeredAt: '5 mins ago',
    createdAt: '2026-06-05',
    createdByName: 'Hiroshi Sato',
    branchScope: 'all',
    status: 'active',
  },
  {
    id: 'rule-2',
    title: 'Auto-Pause Out of Stock Menu Dishes',
    description: 'Instantly disable dish availability in online menu when key ingredient stock reaches zero.',
    triggerEvent: 'inventory.out_of_stock',
    action: 'change_menu_status',
    actionConfig: { autoDisable: true },
    isActive: true,
    runCount: 42,
    lastTriggeredAt: '3 hours ago',
    createdAt: '2026-06-18',
    createdByName: 'Kenji Ueda',
    branchScope: 'all',
    status: 'active',
  },
  {
    id: 'rule-3',
    title: 'SLA Delay Alert to Kitchen Manager',
    description: 'Dispatch high-priority alert if kitchen order prep exceeds 25 minutes.',
    triggerEvent: 'order.delayed',
    action: 'send_notification',
    actionConfig: { priority: 'high' },
    isActive: true,
    runCount: 18,
    lastTriggeredAt: 'Yesterday 19:40',
    createdAt: '2026-07-01',
    createdByName: 'System Admin',
    branchScope: 'all',
    status: 'active',
  },
];

// ─── Initial API Keys ─────────────────────────────────────────────────────────
export const INITIAL_API_KEYS: ApiKeyCredentials[] = [
  {
    id: 'key-1',
    name: 'Production Primary Server Key',
    keyPrefix: 'fst_live_98a2...',
    fullKeySecret: 'fst_live_98a2f4c9103e4881ba8290e1',
    environment: 'production',
    scopes: ['read', 'write', 'admin'],
    createdAt: '2026-06-01',
    lastUsedAt: 'Just now',
    status: 'active',
  },
  {
    id: 'key-2',
    name: 'Sandbox Developer Integration Key',
    keyPrefix: 'fst_test_3b11...',
    fullKeySecret: 'fst_test_3b11094ea9120489912bc781',
    environment: 'sandbox',
    scopes: ['read', 'write'],
    createdAt: '2026-07-10',
    lastUsedAt: '2 days ago',
    status: 'active',
  },
];

// ─── Sync Health Initial Metrics ──────────────────────────────────────────────
export const INITIAL_SYNC_HEALTH: SyncHealthMetrics = {
  lastSyncTimestamp: '2026-07-25 16:25:12',
  syncSuccessRatePct: 99.6,
  avgSyncLagMs: 84,
  failedItemsCount: 2,
  pendingRetryCount: 1,
  conflictCount: 0,
  status: 'healthy',
};

// ─── Initial Activity Logs ────────────────────────────────────────────────────
export const INITIAL_ACTIVITY_LOGS: IntegrationActivityLog[] = [
  { id: 'act-1', sourceApp: 'Stripe Payments', eventType: 'payment_intent.succeeded', message: 'Successfully captured ₹445 for order #1809.', severity: 'success', timestamp: '2 mins ago' },
  { id: 'act-2', sourceApp: 'WhatsApp API', eventType: 'message.delivered', message: 'Dispatched order receipt to +91 9876543210.', severity: 'info', timestamp: '3 mins ago' },
  { id: 'act-3', sourceApp: 'Tally Prime ERP', eventType: 'ledger.sync', message: 'Synchronized daily cash register balances.', severity: 'success', timestamp: '30 mins ago' },
  { id: 'act-4', sourceApp: 'Customer CRM', eventType: 'webhook.timeout', message: 'Delivery failed with 504 Gateway Timeout. Scheduled for retry.', severity: 'warning', timestamp: '1 hour ago' },
];

// ─── Initial Marketplace Apps ─────────────────────────────────────────────────
export const INITIAL_MARKETPLACE: MarketplaceApp[] = [
  { id: 'mk-1', name: 'Shopify POS Sync', category: 'pos', tagline: 'Unified inventory & retail orders for multi-format dining spaces.', rating: 4.9, reviewCount: 128, installed: false, priceModel: 'Freemium', developer: 'Shopify, Inc.', bannerColor: '#5e8e3e', features: ['Realtime stock sync', 'Unified checkout receipt', 'Barcode scanner support'], requiredPermissions: ['read:catalog', 'write:orders'] },
  { id: 'mk-2', name: 'Zendesk Support Desk', category: 'crm', tagline: 'Convert guest feedback & order refund claims directly into support tickets.', rating: 4.7, reviewCount: 84, installed: false, priceModel: 'Paid', developer: 'Zendesk', bannerColor: '#03363d', features: ['Automatic ticket routing', 'Customer SLA tracking', 'Refund workflow integration'], requiredPermissions: ['write:tickets', 'read:customers'] },
  { id: 'mk-3', name: 'Mailchimp Marketing', category: 'messaging', tagline: 'Automated email newsletter campaigns for customer retention.', rating: 4.8, reviewCount: 210, installed: false, priceModel: 'Freemium', developer: 'Intuit Mailchimp', bannerColor: '#ffe01b', features: ['Diner segment sync', 'Automated birthday offers', 'Campaign ROI reports'], requiredPermissions: ['read:customers'] },
];

// ─── Smart AI Insights Placeholders ───────────────────────────────────────────
export const INITIAL_AI_INSIGHTS: SmartAIInsight[] = [
  { id: 'ai-1', title: 'Webhook Timeout Optimization', description: 'Customer CRM webhook endpoint shows 14.8% timeout rate. Recommend increasing timeout limit to 8000ms or switching to async queue.', impactScore: 'high', type: 'retry_optimization', actionLabel: 'Adjust Timeout' },
  { id: 'ai-2', title: 'Automate Out-of-Stock Alerting', description: 'Avocado inventory drops below safety threshold on Tuesdays. Auto-pausing menu items 2 hours early prevents order cancelations.', impactScore: 'medium', type: 'automation_suggestion', actionLabel: 'Enable Rule' },
];
